language: node_js
node_js:
  - '12'
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - npm install -g yarn # make sure yarn is new
  - npm config set spin false
  - npm install -g npm@^6.9.0
script:
  - yarn test-ci
  - yarn build
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: "yL6oe8++Z5kCj6VT2+8B1tUsLDQKjPahWdNtSLPbiEaNxj8rqd10c/zxkonf1CcfUGpg6y7XxWDcmrvmGv4teBZFaB/lzffUEqSLFQo8fQCrIPl/Y1TH/dYofnqobcRL7PvFZ19R036wzuP938YiKj4BTj8htxQG46L5P9g8sRtZ2Cj2gbIhlgxAnXJcmyopq4/bPdPydiz45LdSiSEy8VdAyzN0bw37qpSQFgO3b8gSoGTgxFDBi/PfUtbqk30NusBWeXyN3UgoG/aNkmUGVDWESruu98J9Ufjy7aameLJK4cnW8dGsDaNJudBPCJV0t6gr+UdAMTsRP3F+bUWqQAj3wEiDApNmmm83MTjlvzlgnrqwcwUp7BW0vUZGbMlJi1ntjLifPlStPprLIJzV4otYtDjMIDdF6p+9Vhrbd2IbcQG5WGXkE6v8QFSzILI6KYFlc7cAE2o56xgeTuXr3lddQ8nL1J+yc2j5EvU0Xs0A0jQ8MxUYRe+Ea89LHWid/ttf5fO+M4h9tVVl3UVWZaCZVrQwWckWU18ASqKnVqp7vCKPw2zy0KbpUBVhtN7lv1aRce8sorvm4YLIvba/z7FoSU3KClFWUHQih0upAlPdjABsDRQ3FNwdcFobSHfIVS8I1sMO0WIicYfM186rK3gmJxWEwuEVLLaDzIPDFEM="
  file:
    - build/_output/simple-survey.wigt
    - build/_output/simple-survey-build-info.yml
  on:
    tags: true
    repo: ucfopen/survey-materia-widget
notifications:
  email: false
  slack:
    secure: "TZNKYhgTAzjrMF8qfnuXC4EWB50DT+itTav+34ZR/k4TMBpGmlezoI28bHpuQsdRu9LM9JW7ZaChr0Q291GZdC7Ej6lYJagdwitoLggIvDkfy16lc5G77A81EZ9ZkeOwpgNXDVxllPDF4ioJEwAaZKPnzZwjrqSb2PntCltFu0H1bcDgqFv1Q0JObjhUHrR3JQGJ9y2xZo0SUEtZkfUhdZ1EEurF9LV6QaEUG7cckgtgfgL2Zl3iCNvY14HPmEAGb1mOZXbKcnfngtYF6I62D+SL8aRIYAEJJ7Mbwa5fSN35x+mTLcH3Z8cRnTBP2b1BrKbEy00uTqNDbdp4F4Kh2QCsLjG/nPEoNtjVLojUW7CRrT5eVgezqPkDmE4oKnQAEB1TRF9fEU6uCE+4GQk39yovBocvrcNV3F0ApQ1azjZtDjZg1OpEmOedwJwRxjea/fTLqvaTxZA4XbUXAhkJhn1r+f5qUjIR44J6wPs11Zz+QLb0hQyQVsF18m8NXtg8J59CF6aVPB8x9gbYjd+oeioREJKq2qfiwt0M6yZw+jWN8CRXIvq+yfhajAv8JFkxR543R+BlpIU15aLrBOFJP/M1bnfUg9IIxDvpQLsprtvxGdY7sl3MoCjMT+Ws0FET5Q1O9IrBorf7ho7yyq4phX85HX9TjxD5ml1XQpwa+rQ="
